### PR TITLE
change console credentials to novnc html5

### PR DESCRIPTION
**Pull request by habibulilalbaab**
Admin Side:
image

Client Side:
image

### CODE REVIEW

**Comment by habibulilalbaab** [comment]
hemmm looks not ready yet, we need add cookie pve to working. I'll update later

**Comment by Fedsd1** [comment]
Is it currently working well?

**Comment by Fedsd1** [comment]
I installed it here but it cannot be used normally, as the picture shows a black screen.

**Comment by habibulilalbaab** [comment]
do you get error code after load console ?

**Comment by habibulilalbaab** [comment]
> shows a black screen

do you get error code after load console ?

**Comment by Fedsd1** [comment]
no

________________________________
发件人: Muhammad Habib Ulil A ***@***.***>
发送时间: 2024年1月16日 9:07
收件人: blesta/module-proxmox ***@***.***>
抄送: RDReindeer ***@***.***>; Comment ***@***.***>
主题: Re: [blesta/module-proxmox] change console credentials to novnc html5 (PR #44)


do you get error code after load console ?

―

**Comment by geron74784** [comment]
I have installed it and added the 8006 port in line 45, but i get invalid csrf token error.

**Pull request closed without merging**
